# Generated by Django 4.2 on 2023-04-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_document',
            old_name='created',
            new_name='uploaded_at',
        ),
    ]
