# Generated by Django 4.2 on 2023-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_employee_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_tasks',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
