# Generated by Django 4.2 on 2023-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_employee_tasks_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('EmployeeId', models.IntegerField()),
                ('document', models.BinaryField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
